# Generated by Django 5.1 on 2024-09-08 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0015_remove_jobposting_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationRequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('accreditation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.accreditationrequest')),
            ],
        ),
    ]
