# Generated by Django 5.1 on 2024-09-09 15:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesostaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationrequestapproval',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/uploads/'), upload_to='documents/'),
        ),
    ]
