# Generated by Django 5.1 on 2024-09-09 15:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesostaff', '0002_accreditationrequestapproval_uploaded_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationrequestapproval',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/accreditation_documents/'), upload_to='documents/'),
        ),
    ]
