# Generated by Django 5.1 on 2024-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesostaff', '0003_alter_accreditationrequestapproval_uploaded_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationrequestapproval',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, upload_to='approval_documents/'),
        ),
    ]
