# Generated by Django 5.1 on 2024-10-13 14:10

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/resume_documents/'), upload_to='')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobseeker.resumedocument'),
        ),
    ]
