# Generated by Django 5.1 on 2024-10-22 07:41

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_resumedocument_alter_jobseekerprofile_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('started', models.DateField(blank=True, default='', null=True)),
                ('finished', models.DateField(blank=True, default='', null=True)),
                ('program', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_one', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hired', models.DateField(blank=True, default='', null=True)),
                ('resigned', models.DateField(blank=True, default='', null=True)),
                ('role', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobseeker.resumedocument'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumedocument',
            name='resume',
            field=models.FileField(blank=True, default='', null=True, storage=django.core.files.storage.FileSystemStorage(location='media/resume_documents/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='resumedocument',
            name='resume_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educ', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobseeker.education')),
            ],
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='educ',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobseeker.educationhistory'),
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobseeker.employment')),
            ],
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobseeker.employmenthistory'),
        ),
    ]
