# Generated by Django 5.1 on 2024-10-24 05:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_education_employment_resumedocument_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='company_one',
            new_name='company',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='finished',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='educ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.education'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='hired',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='resigned',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
