# Generated by Django 5.1 on 2024-10-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_educationhistory_user_employmenthistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationhistory',
            name='educ',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobseeker.education'),
        ),
    ]
