# Generated by Django 5.1 on 2024-10-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0011_alter_education_user_alter_educationhistory_educ_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumedocument',
            old_name='educ',
            new_name='educ_his',
        ),
        migrations.RenameField(
            model_name='resumedocument',
            old_name='work',
            new_name='work_his',
        ),
    ]
