# Generated by Django 5.1 on 2024-11-05 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0012_rename_educ_resumedocument_educ_his_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedocument',
            name='educ_his',
        ),
        migrations.RemoveField(
            model_name='employmenthistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employmenthistory',
            name='work',
        ),
        migrations.RemoveField(
            model_name='resumedocument',
            name='work_his',
        ),
        migrations.RemoveField(
            model_name='resumedocument',
            name='resume_text',
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employment',
            name='resigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumedocument',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume_document_storage'),
        ),
        migrations.AlterField(
            model_name='resumedocument',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='resume_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EducationHistory',
        ),
        migrations.DeleteModel(
            name='EmploymentHistory',
        ),
    ]
