# Generated by Django 5.1 on 2024-11-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0013_remove_resumedocument_educ_his_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedocument',
            name='educ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_documents', to='jobseeker.education'),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_documents', to='jobseeker.employment'),
        ),
    ]
