# Generated by Django 5.1 on 2024-11-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0015_jobseekerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
