# Generated by Django 5.1 on 2024-11-23 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0016_jobseekerprofile_phone_jobseekerprofile_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resumedocument',
            name='educ',
        ),
        migrations.RemoveField(
            model_name='resumedocument',
            name='work',
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='jobseeker.resumedocument'),
        ),
        migrations.AddField(
            model_name='employment',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment_entries', to='jobseeker.resumedocument'),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_documents', to='jobseeker.resumedocument'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumedocument',
            name='location',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='resumedocument',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='resume_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
