# Generated by Django 5.1 on 2025-01-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0017_remove_jobseekerprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_entries', to='jobseeker.resumedocument'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='resume',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_entries', to='jobseeker.resumedocument'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='jobseeker.resumedocument'),
        ),
    ]
