# Generated by Django 5.1 on 2024-08-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_user',
            new_name='is_staff',
        ),
    ]
