# Generated by Django 5.1 on 2024-08-26 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationrequest',
            name='company_type',
            field=models.CharField(default='Default Type', max_length=255),
        ),
        migrations.CreateModel(
            name='MatchedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('matched_date', models.DateField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_candidates', to='employer.applicant')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_candidates', to='employer.jobposting')),
            ],
        ),
        migrations.DeleteModel(
            name='InterviewSchedule',
        ),
    ]
