# Generated by Django 5.1 on 2024-08-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_jobposting_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationrequest',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='company_type',
            field=models.CharField(choices=[('Type1', 'Type1'), ('Type2', 'Type2'), ('Type3', 'Type3')], default='Type1', max_length=255),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='document',
            field=models.FileField(upload_to='accreditation_documents/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
