# Generated by Django 5.1 on 2024-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_accreditationrequest_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/'),
        ),
    ]
