# Generated by Django 5.1 on 2024-08-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_accreditationrequest_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationrequest',
            name='document',
            field=models.FileField(upload_to='accreditation_documents/'),
        ),
    ]
