# Generated by Django 5.0.7 on 2024-08-28 04:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_accreditationrequest_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationrequest',
            name='document',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/accreditation_documents/'), upload_to='accreditation_documents/'),
        ),
    ]
