# Generated by Django 5.1 on 2024-08-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_accreditationrequest_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationrequest',
            name='bir_registration',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/bir_registration/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='business_permit',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/business_permit/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='dole_permit',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/dole_permit/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='dti_permit',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/dti_permit/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='latest_job_posting',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/latest_job_posting/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='no_pending_case_certificate',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/no_pending_case_certificate/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='phil_job_net_registration',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/phil_job_net_registration/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='poea_permit',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/poea_permit/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='sec_registration',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/sec_registration/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='tied_companies_list',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/tied_companies_list/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='company_type',
            field=models.CharField(choices=[('Direct Company', 'Direct Company'), ('Manpower Agencies/Cooperative', 'Manpower Agencies/Cooperative'), ('For Overseas Manpower Agency', 'For Overseas Manpower Agency')], default='Type1', max_length=255),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
