# Generated by Django 5.1 on 2024-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_accreditationrequest_bir_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditationrequest',
            name='document',
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='company_type',
            field=models.CharField(choices=[('Direct Company', 'Direct Company'), ('Manpower Agencies/Cooperative', 'Manpower Agencies/Cooperative'), ('For Overseas Manpower Agency', 'For Overseas Manpower Agency')], default='Direct Company', max_length=255),
        ),
    ]
