# Generated by Django 5.1 on 2024-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_remove_accreditationrequest_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationrequest',
            name='poea_permit_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
