# Generated by Django 5.1 on 2024-09-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_accreditationrequest_poea_permit_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditationrequest',
            name='document_text',
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='bir_registration_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='dole_permit_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='latest_job_posting_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='no_pending_case_certificate_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='phil_job_net_registration_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='tied_companies_list_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
