# Generated by Django 5.1 on 2024-09-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_remove_accreditationrequest_document_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditationrequest',
            name='bir_registration_text',
        ),
        migrations.RemoveField(
            model_name='accreditationrequest',
            name='dole_permit_text',
        ),
        migrations.RemoveField(
            model_name='accreditationrequest',
            name='latest_job_posting_text',
        ),
        migrations.RemoveField(
            model_name='accreditationrequest',
            name='no_pending_case_certificate_text',
        ),
        migrations.RemoveField(
            model_name='accreditationrequest',
            name='phil_job_net_registration_text',
        ),
        migrations.RemoveField(
            model_name='accreditationrequest',
            name='poea_permit_text',
        ),
        migrations.RemoveField(
            model_name='accreditationrequest',
            name='tied_companies_list_text',
        ),
    ]
