# Generated by Django 5.1 on 2024-09-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_remove_accreditationrequest_bir_registration_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationrequest',
            name='latest_job_order_with_qualifications',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/latest_job_order_with_qualifications/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='latest_payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/latest_payment_receipt/'),
        ),
        migrations.AddField(
            model_name='accreditationrequest',
            name='sss_membership_registration',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/sss_membership_registration/'),
        ),
    ]
