# Generated by Django 5.1 on 2024-09-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0014_alter_accreditationrequest_bir_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='company',
        ),
    ]
