# Generated by Django 5.1 on 2024-09-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_remove_jobposting_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationrequest',
            name='business_permit',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/business_permit/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='dole_permit',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/dole_permit/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='dti_permit',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/dti_permit/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='latest_job_order_with_qualifications',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/latest_job_order_with_qualifications/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='no_pending_case_certificate',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/no_pending_case_certificate/'),
        ),
    ]
