# Generated by Django 5.1 on 2024-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0016_alter_accreditationrequest_business_permit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationrequest',
            name='bir_registration',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/bir_registration/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='latest_job_posting',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/latest_job_posting/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='latest_payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/latest_payment_receipt/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='phil_job_net_registration',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/phil_job_net_registration/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='poea_permit',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/poea_permit/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='sec_registration',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/sec_registration/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='sss_membership_registration',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/sss_membership_registration/'),
        ),
        migrations.AlterField(
            model_name='accreditationrequest',
            name='tied_companies_list',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_documents/tied_companies_list/'),
        ),
    ]
