# Generated by Django 5.1 on 2024-09-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0017_alter_accreditationrequest_bir_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationrequest',
            name='document_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
