# Generated by Django 5.1 on 2024-09-30 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0019_remove_companyprofile_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
