# Generated by Django 5.1 on 2024-09-30 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0020_remove_companyprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='date_established',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
