# Generated by Django 5.1 on 2025-01-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0021_alter_companyprofile_date_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employer.companyprofile'),
        ),
    ]
