# Generated by Django 5.1 on 2025-01-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0022_jobposting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='industry',
        ),
    ]
